### ISSUE TITLE
Update android:minSdkVersion and :targetSdkVersion to match m-c

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fennec-search#2]
This is pretty simple, but I'd like this code to compile warning free (with `-Xlint:all`) before landing.  You can use the WIP patches to see the warnings I'm seeing during the build.  It will be best if the `gradle` and IDE configurations are the same as m-c, although that could be tricky.

**Comment by EricEdens** [comment]
Fixed with https://github.com/ericedens/FirefoxSearch/commit/02b12d57286dbbfa5e8bf2795372fd9ed784b923
