### ISSUE TITLE
Move special `Configuration.java` properties into gradle-generated BuildConfig

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fennec-search#3]
I see that the `gradle` way of including build-time configuration is using BuildConfig.  For a simple (documented!) example, see `https://github.com/mozilla/MozStumbler/`.  They include API keys just like you want in `gradle.properties` and then generate `BuildConfig.java` from those properties.  This project should follow suit; flag me for review.

**Comment by EricEdens** [comment]
The current milestone for landing in M-C doesn't use any external APIs; so I'll close this for now, but we'll want to address this when we do add third-party APIs
