### ISSUE TITLE
Update `AndroidManifest.xml` to refer to full package name

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fennec-search#4]
It's not 100% clear how we'll integrate `org.mozilla.search` into Fennec, but we almost certainly will manually merge bits of the manifests together.  That means that relative activity paths (like `.Activity` and `.HistoryService`) won't work, 'cuz they'll be resolved relative to the package name, which varies (like `org.mozilla.firefox` and `org.mozilla.firefox_beta`).  These references will need to be absolute, like `org.mozilla.search.Activity`.

This ticket depends on #1.

**Comment by EricEdens** [comment]
Fixed in https://github.com/ericedens/FirefoxSearch/commit/85c054cca3db396cb5e27b94cbf3ee470e57b29a
