### ISSUE TITLE
License fragment headers throughout

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fennec-search#6]
MPL for Java (part of Fennec), PD for test-only code.

https://github.com/mozilla-services/android-sync/blob/develop/tools/COPYRIGHT_MPL
https://github.com/mozilla-services/android-sync/blob/develop/tools/COPYRIGHT_PD

**Comment by EricEdens** [comment]
Issue moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1031534
