### ISSUE TITLE
No rule to make target `.project' when building fennec release

### ISSUE THREAD

**Issue by ivantsar** [mozilla/fennec-search#89]
I'm building sources from http://hg.mozilla.org/releases/mozilla-release/ and get the following error: 

make[5]: **\* No rule to make target `.project', needed by`/Users/yu/Documents/projects/mozilla/Fennec/release/obj-arm-linux-androideabi/mobile/android/geckoview_library/.project'.  Stop 

My mozconfig looks like this: 

ac_add_options --with-android-ndk="$HOME/Development/android-ndk-r8e" 
 ac_add_options --with-android-sdk="$HOME/Development/sdk/platforms/android-17" 

 ac_add_options --enable-application=mobile/android 
 ac_add_options --target=arm-linux-androideabi 

ac_add_options --disable-tests 
export MOZ_DISABLE_GECKOVIEW=1 

last two options were added trying to troubleshoot.

I can build nightly sources with this mozconfig. I can also build release sources without mozconfig, 
But I cannot build release Fennec for Android 

HerHere is the build log: 
https://justpaste.it/gv89

**Comment by leibovic** [comment]
This repo is for the standalone search activity, so this isn't the right place to ask for help building Firefox. You should join #mobile on irc.mozilla.org or post to [mobile-firefox-dev](https://mail.mozilla.org/listinfo/mobile-firefox-dev) to ask for help.
